spring.application.name=tunisair-billets

spring.datasource.url=jdbc:mysql://localhost:3306/tunisair_billets
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
file.upload-dir=C:/uploads
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raniagharbi718@gmail.com
spring.mail.password=lhzdxwbhgspmltlt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true